[[redirects]]
  from = "https://www.automate-hub.com/*"
  to = "https://automate-hub.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://automate-hub.com/*"
  to = "https://automate-hub.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.automate-hub.com/*"
  to = "https://automate-hub.com/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Enable XSS protection (legacy browsers)
    X-XSS-Protection = "1; mode=block"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Strict Transport Security - Force HTTPS for 2 years
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # Restrict browser features (allow microphone for Vapi calls)
    Permissions-Policy = "camera=(), microphone=(self), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Content Security Policy - Enhanced security with violation reporting
           Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://analytics.google.com https://vg-bunny-cdn.b-cdn.net https://vapi.ai https://*.vapi.ai; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://vg-bunny-cdn.b-cdn.net; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; media-src 'self' https://*.vapi.ai blob:; connect-src 'self' https://*.supabase.co https://*.supabase.in https://vapi.ai https://*.vapi.ai wss://*.vapi.ai https://www.google-analytics.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests; block-all-mixed-content; report-uri /csp-report;"
           Cross-Origin-Embedder-Policy = "require-corp"
           Cross-Origin-Opener-Policy = "same-origin"
           Cross-Origin-Resource-Policy = "same-origin"
    
    # Prevent DNS prefetching for privacy
    X-DNS-Prefetch-Control = "off"
    
    # Download options for IE
    X-Download-Options = "noopen"
    
    # Permitted cross-domain policies
    X-Permitted-Cross-Domain-Policies = "none"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/.well-known/security.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

