services:
  - type: web
    name: automate-hub
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://analytics.google.com https://vg-bunny-cdn.b-cdn.net; style-src 'self' 'unsafe-inline' https://vg-bunny-cdn.b-cdn.net; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://*.supabase.in;"

